version: "3.8"

services:
  app:
    build: .
    ports:
      - "6000:6000"
    environment:
      - NODE_ENV=production
      - TAILSCALE_API_KEY=${TAILSCALE_API_KEY}
      - TAILSCALE_TAILNET=${TAILSCALE_TAILNET}
      - DATABASE_URL=${DATABASE_URL:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/network/stats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: PostgreSQL database
  # Uncomment if you want to use a persistent database instead of in-memory storage
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: tailscale_dashboard
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped
# volumes:
#   postgres_data:
