global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'tailscale-dashboard'
    static_configs:
      - targets: ['tailscale-dashboard:5000']
    scrape_interval: 30s
    metrics_path: '/metrics'
    scheme: 'http'